#!/bin/sh
# required
mv ~/.config/nvim.bak ~/.config/nvim

# optional but recommended
mv ~/.local/share/nvim.bak ~/.local/share/nvim
mv ~/.local/state/nvim.bak ~/.local/state/nvim
mv ~/.cache/nvim.bak ~/.cache/nvim
